#ifndef ACTION_PARSER_H
#define ACTION_PARSER_H

enum ActionParser {
    SEARCH_ATTRIBUTE_NAME,
    SEARCH_ATTRIBUTE_QUOT,
    SEARCH_ATTRIBUTE_VALUE,
    SAVE_ATTRIBUTE_WITH_NO_VALUE,
    SAVE_ATTRIBUTE_WITH_VALUE
};

#endif